/* ============================================
   Physiotherapy Autocomplete Terms Database
   Organized by SOAP note field context
   ============================================ */
window.PhysioTerms = (function() {

  // --- Subjective terms (patient reports) ---
  var subjective = [
    'Patient complains of sharp pain',
    'Patient complains of dull aching pain',
    'Patient reports throbbing pain',
    'Patient reports burning sensation',
    'Patient complains of shooting pain',
    'Patient reports tingling and numbness',
    'Patient complains of radiating pain',
    'Patient reports stiffness',
    'Patient complains of constant pain',
    'Patient reports intermittent pain',
    'Patient complains of pain at rest',
    'Patient reports pain on movement',
    'Patient reports night pain disturbing sleep',
    'Patient complains of morning stiffness',
    'Patient reports pain aggravated by activity',
    'Patient reports pain relieved by rest',
    'Patient complains of weakness',
    'Patient reports swelling',
    'Patient reports grinding/crepitus sensation',
    // VAS
    'VAS 0/10 - No pain',
    'VAS 1/10 - Minimal pain',
    'VAS 2/10 - Mild pain',
    'VAS 3/10 - Mild pain',
    'VAS 4/10 - Moderate pain',
    'VAS 5/10 - Moderate pain',
    'VAS 6/10 - Moderate-severe pain',
    'VAS 7/10 - Severe pain',
    'VAS 8/10 - Severe pain',
    'VAS 9/10 - Very severe pain',
    'VAS 10/10 - Worst imaginable pain',
    // Functional
    'Difficulty in walking',
    'Difficulty in climbing stairs',
    'Difficulty in sitting for prolonged periods',
    'Difficulty in standing for prolonged periods',
    'Difficulty in getting up from chair',
    'Difficulty in getting up from floor',
    'Difficulty in squatting',
    'Difficulty in cross-legged sitting',
    'Difficulty in overhead activities',
    'Difficulty in combing hair',
    'Difficulty in reaching behind back',
    'Difficulty in lifting objects',
    'Difficulty in turning neck',
    'Difficulty in sleeping on affected side',
    'Difficulty in gripping objects',
    'Unable to perform ADLs independently',
    'Unable to perform work duties',
    'Difficulty in using Indian toilet',
    'Difficulty in performing household chores',
    // Onset
    'Sudden onset',
    'Gradual onset',
    'Insidious onset',
    'H/o trauma',
    'H/o fall',
    'H/o road traffic accident (RTA)',
    'H/o sports injury',
    'H/o surgery',
    'H/o prolonged immobilization',
    'H/o repetitive strain',
    'Symptoms since last visit - improved',
    'Symptoms since last visit - same',
    'Symptoms since last visit - worsened',
    'No significant medical history',
    'H/o diabetes mellitus',
    'H/o hypertension',
    'Known case of osteoarthritis',
    'Known case of rheumatoid arthritis',
    // Aggravating/Relieving
    'Aggravated by prolonged sitting',
    'Aggravated by prolonged standing',
    'Aggravated by walking',
    'Aggravated by climbing stairs',
    'Aggravated by bending forward',
    'Aggravated by overhead activities',
    'Aggravated by lifting',
    'Aggravated by cold weather',
    'Relieved by rest',
    'Relieved by medication',
    'Relieved by hot fomentation',
    'Relieved by change of position',
    'Relieved by ice application'
  ];

  // --- Objective terms (clinical findings) ---
  var objective = [
    // Observation
    'Antalgic gait observed',
    'Trendelenburg gait observed',
    'Limping gait observed',
    'Normal gait pattern',
    'Forward head posture',
    'Rounded shoulders',
    'Increased lumbar lordosis',
    'Reduced lumbar lordosis (flat back)',
    'Thoracic kyphosis increased',
    'Scoliosis noted',
    'Lateral pelvic tilt',
    'Muscle wasting observed',
    'Muscle atrophy noted',
    'Swelling present',
    'Oedema present',
    'Effusion present',
    'Tenderness on palpation',
    'Warmth over the joint',
    'Muscle spasm palpated',
    'Trigger points identified',
    'Crepitus felt on movement',
    // ROM
    'Cervical flexion ROM',
    'Cervical extension ROM',
    'Cervical lateral flexion R/L ROM',
    'Cervical rotation R/L ROM',
    'Shoulder flexion ROM',
    'Shoulder extension ROM',
    'Shoulder abduction ROM',
    'Shoulder internal rotation ROM',
    'Shoulder external rotation ROM',
    'Elbow flexion ROM',
    'Elbow extension ROM',
    'Wrist flexion ROM',
    'Wrist extension ROM',
    'Hip flexion ROM',
    'Hip extension ROM',
    'Hip abduction ROM',
    'Hip internal rotation ROM',
    'Hip external rotation ROM',
    'Knee flexion ROM',
    'Knee extension ROM',
    'Ankle dorsiflexion ROM',
    'Ankle plantarflexion ROM',
    'Lumbar flexion ROM',
    'Lumbar extension ROM',
    'Lumbar lateral flexion R/L ROM',
    'AROM - within normal limits',
    'AROM - restricted',
    'PROM - within normal limits',
    'PROM - restricted',
    'ROM limited by pain',
    'ROM limited by stiffness',
    'Full ROM achieved',
    // MMT
    'MMT Grade 0/5 - No contraction',
    'MMT Grade 1/5 - Trace/flicker',
    'MMT Grade 2/5 - Poor (gravity eliminated)',
    'MMT Grade 3/5 - Fair (against gravity)',
    'MMT Grade 4/5 - Good (against moderate resistance)',
    'MMT Grade 5/5 - Normal (full resistance)',
    'Grip strength - weak',
    'Grip strength - good',
    'Core strength - poor',
    'Core strength - fair',
    'Core strength - good',
    // Special Tests
    'SLR test - positive',
    'SLR test - negative',
    'Neer\'s impingement test - positive',
    'Hawkins-Kennedy test - positive',
    'Empty can test - positive',
    'Speed\'s test - positive',
    'Apprehension test - positive',
    'Spurling\'s test - positive',
    'Anterior drawer test - positive',
    'Posterior drawer test - positive',
    'Lachman\'s test - positive',
    'McMurray\'s test - positive',
    'Valgus stress test - positive',
    'Varus stress test - positive',
    'Thomas test - positive',
    'FABER/Patrick\'s test - positive',
    'Ober\'s test - positive',
    'Tinel\'s sign - positive',
    'Phalen\'s test - positive',
    'Finkelstein\'s test - positive',
    'Slump test - positive',
    'Romberg test - positive',
    // Neuro
    'Sensation intact',
    'Sensation diminished',
    'Deep tendon reflexes - normal',
    'Deep tendon reflexes - diminished',
    'Deep tendon reflexes - exaggerated',
    'Tone - normal',
    'Tone - increased (spasticity)',
    'Tone - decreased (flaccidity)',
    'Balance - good',
    'Balance - fair',
    'Balance - poor',
    'Coordination - intact',
    'Coordination - impaired',
    'Proprioception - intact',
    'Proprioception - impaired',
    // Functional
    'Gait assessment - independent',
    'Gait assessment - with assistive device',
    'Transfer - independent',
    'Transfer - with minimal assist',
    'Sit to stand - independent',
    'Sit to stand - with difficulty',
    'Stair climbing - independent',
    'Stair climbing - with rail support',
    'Single leg stance - seconds'
  ];

  // --- Assessment terms (clinical impression) ---
  var assessment = [
    // Conditions
    'Consistent with mechanical low back pain',
    'Consistent with cervical spondylosis',
    'Consistent with lumbar radiculopathy',
    'Consistent with cervical radiculopathy',
    'Consistent with rotator cuff tendinopathy',
    'Consistent with adhesive capsulitis (frozen shoulder)',
    'Consistent with impingement syndrome',
    'Consistent with osteoarthritis',
    'Consistent with ligament sprain',
    'Consistent with muscle strain',
    'Consistent with myofascial pain syndrome',
    'Consistent with postural dysfunction',
    'Consistent with degenerative disc disease',
    'Consistent with disc prolapse/herniation',
    'Consistent with patellofemoral pain syndrome',
    'Consistent with IT band syndrome',
    'Consistent with plantar fasciitis',
    'Consistent with Achilles tendinopathy',
    'Consistent with tennis elbow (lateral epicondylitis)',
    'Consistent with golfer\'s elbow (medial epicondylitis)',
    'Consistent with carpal tunnel syndrome',
    'Consistent with De Quervain\'s tenosynovitis',
    'Consistent with piriformis syndrome',
    'Consistent with sacroiliac joint dysfunction',
    'Post TKR rehabilitation',
    'Post THR rehabilitation',
    'Post ACL reconstruction rehabilitation',
    'Post fracture rehabilitation',
    'Post stroke rehabilitation',
    'Bell\'s palsy recovery',
    'Peripheral neuropathy',
    // Progress
    'Patient is progressing well',
    'Patient is progressing slowly',
    'Patient showing improvement in ROM',
    'Patient showing improvement in strength',
    'Patient showing improvement in functional abilities',
    'Patient reports decrease in pain',
    'Patient reports increase in pain',
    'No significant improvement noted',
    'Condition is stable',
    'Patient is compliant with HEP',
    'Patient is non-compliant with HEP',
    'Treatment goals being met',
    'Treatment goals partially met',
    'Requires continued physiotherapy',
    'Patient tolerating treatment well',
    'Plateau in progress noted',
    'Ready for progression to next phase',
    // Severity
    'Mild condition',
    'Moderate condition',
    'Severe condition',
    'Acute phase',
    'Sub-acute phase',
    'Chronic condition',
    'Acute on chronic',
    'Recurrent episode',
    'Bilateral involvement',
    'Unilateral involvement - right',
    'Unilateral involvement - left'
  ];

  // --- Plan terms (treatment plan) ---
  var plan = [
    // Electrotherapy
    'IFT (Interferential Therapy)',
    'TENS (Transcutaneous Electrical Nerve Stimulation)',
    'Ultrasound therapy (US)',
    'Combination therapy (US + IFT)',
    'Combination therapy (US + TENS)',
    'Muscle stimulator (MS/EMS)',
    'Shortwave diathermy (SWD)',
    'LASER therapy (low-level)',
    'Shockwave therapy (ESWT)',
    'Traction - cervical',
    'Traction - lumbar',
    'Wax bath (paraffin wax therapy)',
    'NMES (Neuromuscular electrical stimulation)',
    // Thermal
    'Hot pack (moist heat)',
    'Cold pack (cryotherapy)',
    'Contrast bath',
    'Infrared radiation (IRR)',
    // Manual Therapy
    'Joint mobilization - Grade I',
    'Joint mobilization - Grade II',
    'Joint mobilization - Grade III',
    'Joint mobilization - Grade IV',
    'Maitland mobilization',
    'Mulligan mobilization with movement (MWM)',
    'Myofascial release (MFR)',
    'Soft tissue mobilization (STM)',
    'Deep tissue massage',
    'Trigger point release',
    'Cross-friction massage',
    'Muscle energy technique (MET)',
    'Neural mobilization/neurodynamics',
    'Dry needling',
    'Kinesiology taping',
    'Stretching - static',
    'Stretching - dynamic',
    'Stretching - PNF (contract-relax)',
    // Exercises
    'Isometric exercises',
    'Isotonic exercises - concentric',
    'Isotonic exercises - eccentric',
    'Active ROM exercises',
    'Active-assisted ROM exercises',
    'Passive ROM exercises',
    'Pendulum exercises (Codman\'s)',
    'Wall climbing exercises',
    'Theraband exercises (resistance band)',
    'Core strengthening exercises',
    'Quadriceps strengthening (SLR, quad sets)',
    'Hamstring strengthening',
    'VMO strengthening',
    'Calf raises',
    'Hip abductor strengthening',
    'Rotator cuff strengthening',
    'Scapular stabilization exercises',
    'McKenzie exercises (extension protocol)',
    'Williams flexion exercises',
    'Chin tucks / cervical retraction',
    'Nerve gliding/flossing exercises',
    'Balance training exercises',
    'Proprioception exercises',
    'Gait training',
    'Functional training',
    'Breathing exercises',
    'Postural correction exercises',
    // Frequency
    'Daily sessions',
    'Alternate day sessions',
    '3 times/week',
    '2 times/week',
    'Once a week',
    '10 sessions planned',
    '12 sessions planned',
    '15 sessions planned',
    'Review after 1 week',
    'Review after 2 weeks',
    'Review after 1 month',
    // Goals
    'Reduce pain',
    'Reduce swelling/inflammation',
    'Improve ROM',
    'Restore full ROM',
    'Improve muscle strength',
    'Improve flexibility',
    'Improve balance and proprioception',
    'Improve functional mobility',
    'Restore normal gait pattern',
    'Return to work activities',
    'Return to sports activities',
    'Improve posture',
    'Prevent recurrence',
    'Home exercise program (HEP) given',
    'Ergonomic modifications advised',
    'Activity modification advised',
    'Brace/support recommended',
    'Referral to specialist',
    'Discharge from physiotherapy',
    // Education
    'HEP explained and demonstrated',
    'Posture correction advice given',
    'Ergonomic advice for workstation',
    'Sleeping position advice given',
    'Lifting technique education',
    'Ice/heat application advice given',
    'Joint protection techniques taught',
    'Precautions explained post-surgery'
  ];

  // --- Diagnosis terms (patient form) ---
  var diagnosis = [
    'Cervical spondylosis',
    'Cervical radiculopathy',
    'Cervical disc prolapse',
    'Torticollis/wry neck',
    'Mechanical low back pain',
    'Lumbar spondylosis',
    'Lumbar disc prolapse/herniation',
    'Lumbar radiculopathy/sciatica',
    'Lumbar canal stenosis',
    'Spondylolisthesis',
    'Ankylosing spondylitis',
    'Frozen shoulder (adhesive capsulitis)',
    'Rotator cuff tear/tendinopathy',
    'Shoulder impingement syndrome',
    'Shoulder dislocation/instability',
    'Subacromial bursitis',
    'Tennis elbow (lateral epicondylitis)',
    'Golfer\'s elbow (medial epicondylitis)',
    'Carpal tunnel syndrome',
    'De Quervain\'s tenosynovitis',
    'Trigger finger',
    'Osteoarthritis - knee',
    'Osteoarthritis - hip',
    'Total knee replacement (TKR) - post-op',
    'Total hip replacement (THR) - post-op',
    'ACL tear/reconstruction',
    'Meniscus tear',
    'Patellofemoral pain syndrome (PFPS)',
    'IT band syndrome',
    'Patellar tendinitis (jumper\'s knee)',
    'Ligament sprain - ankle',
    'Achilles tendinopathy',
    'Plantar fasciitis',
    'Calcaneal spur',
    'Fracture - post-immobilization',
    'Post-fracture stiffness',
    'Myofascial pain syndrome',
    'Fibromyalgia',
    'Piriformis syndrome',
    'Trochanteric bursitis',
    'Sacroiliac joint dysfunction',
    'Rheumatoid arthritis',
    'Stroke/CVA - hemiplegia',
    'Spinal cord injury - paraplegia',
    'Parkinson\'s disease',
    'Bell\'s palsy',
    'Peripheral neuropathy',
    'Diabetic neuropathy',
    'Cerebral palsy',
    'COPD - pulmonary rehabilitation',
    'Post-COVID rehabilitation',
    'Post-surgical rehabilitation',
    'Sports injury',
    'Repetitive strain injury (RSI)',
    'Vertigo/BPPV',
    'Postural dysfunction',
    'Pregnancy-related back pain'
  ];

  // --- Treatment plan terms (patient form) ---
  var treatmentPlan = plan.slice(0); // reuse plan terms

  // --- General/all fields ---
  var general = [
    'Right side',
    'Left side',
    'Bilateral',
    'Within normal limits (WNL)',
    'Not applicable',
    'Cervical spine',
    'Thoracic spine',
    'Lumbar spine',
    'Lumbosacral spine',
    'Sacroiliac joint',
    'Shoulder joint',
    'Elbow joint',
    'Wrist joint',
    'Hip joint',
    'Knee joint',
    'Ankle joint'
  ];

  return {
    subjective: subjective,
    objective: objective,
    assessment: assessment,
    plan: plan,
    diagnosis: diagnosis,
    treatmentPlan: treatmentPlan,
    general: general,
    // Get terms for a specific context
    getTerms: function(context) {
      var terms = [];
      if (context && this[context]) {
        terms = terms.concat(this[context]);
      }
      terms = terms.concat(general);
      return terms;
    }
  };

})();
